/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Guyscreamingmouthopensculpt.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BibiModels/Guyscreamingmouthopensculpt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Quad_Sphere.geometry} material={materials.Material} position={[0, 5.61, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0.349, 5.61, 0.764]} rotation={[Math.PI / 2, 0, -0.107]} scale={0.166} />
      <mesh geometry={nodes.Cube.geometry} material={nodes.Cube.material} position={[-0.048, 4.985, 0.986]} rotation={[-0.05, 0, -0.051]} scale={[0.055, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube001.geometry} material={nodes.Cube001.material} position={[-0.139, 4.991, 0.953]} rotation={[-0.049, -0.216, -0.04]} scale={[0.055, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube002.geometry} material={nodes.Cube002.material} position={[0.118, 4.984, 0.977]} rotation={[-0.026, 0.349, -0.154]} scale={[0.055, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} position={[-0.044, 4.608, 0.839]} rotation={[0.371, -0.225, -3.109]} scale={[0.049, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube004.geometry} material={nodes.Cube004.material} position={[-0.13, 4.599, 0.815]} rotation={[0.367, -0.231, -3.127]} scale={[0.049, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} position={[0.035, 4.598, 0.842]} rotation={[0.357, 0.202, -3.109]} scale={[0.043, 0.055, 0.013]} />
      <mesh geometry={nodes.Cube006.geometry} material={nodes.Cube006.material} position={[0.176, 4.96, 0.923]} rotation={[0.013, 0.609, -0.154]} scale={[0.05, 0.05, 0.012]} />
    </group>
  )
}

useGLTF.preload('/BibiModels/Guyscreamingmouthopensculpt.glb')
