/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 public/BibiModels/HandSculpt.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BibiModels/HandSculpt.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={nodes.Sphere.material} position={[0.158, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/BibiModels/HandSculpt.glb')
