/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 KlausHouse.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/KlausHouse.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground.geometry} material={materials.Snow} position={[0.435, 0.897, 0.419]} scale={[1.568, 1, 1.182]} />
      <mesh geometry={nodes.Mball003.geometry} material={materials.Snow} position={[1.549, 2.631, 1.052]} scale={0.358} />
      <mesh geometry={nodes.Plane002.geometry} material={materials['Material.001']} position={[4.147, 4.033, -8.896]} rotation={[Math.PI / 2, 0, 0.298]} scale={[5.829, 3.157, 3.583]} />
      <mesh geometry={nodes.Mball001.geometry} material={materials.Snow} position={[1.549, 2.631, 1.052]} scale={0.358} />
      <mesh geometry={nodes.Cube.geometry} material={materials.raw_plank_wall} position={[0, 3.573, 0]} />
      <mesh geometry={nodes.Cube003.geometry} material={materials.Structure} position={[-0.159, 2.448, 0.968]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube004.geometry} material={materials.Sign} position={[0.675, 3.839, 1.424]} rotation={[0, 0, -Math.PI]} scale={[-0.288, -0.131, -0.011]}>
        <mesh geometry={nodes.Cylinder.geometry} material={nodes.Cylinder.material} position={[-0.97, 0.964, 0.293]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-0.127, -2.023, -0.279]} />
      </mesh>
      <mesh geometry={nodes.Cube005.geometry} material={materials.Structure} position={[-1.103, 2.448, 0.968]} rotation={[0, 0, 0.236]} />
      <mesh geometry={nodes.Cube006.geometry} material={materials['Brushed Copper']} position={[0.707, 5.221, 1.619]} scale={[0.027, 0.153, 0.027]} />
      <mesh geometry={nodes.Cube007.geometry} material={materials.Structure} position={[-0.148, 3.532, 1.376]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Plane.geometry} material={materials.Wood} position={[0.667, 2.592, 1.244]} scale={[0.865, 0.803, 0.245]} />
      <mesh geometry={nodes.Cube008.geometry} material={materials.Wood} position={[-1.435, 2.364, 0.827]} rotation={[-0.193, 0.03, -0.61]} scale={[1, 2.828, 1]} />
      <mesh geometry={nodes.Cube009.geometry} material={materials.Structure} position={[0.417, 3.532, 1.376]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Wood} position={[0.741, 2.459, 1.606]} scale={[0.357, 0.949, 0.097]} />
      <mesh geometry={nodes.Cube010.geometry} material={materials.Structure} position={[0.489, 3.075, 1.376]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube011.geometry} material={materials.Structure} position={[1.06, 3.532, 1.376]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube012.geometry} material={materials.Structure} position={[1.625, 3.532, 1.376]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube013.geometry} material={materials.Structure} position={[1.697, 3.075, 1.376]} rotation={[0, 0, -Math.PI / 2]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube016.geometry} material={materials.Wood} position={[-1.435, 2.364, 0.133]} rotation={[0.092, -0.167, -0.621]} scale={[1, 2.828, 1]} />
      <mesh geometry={nodes.Cube019.geometry} material={materials.Structure} position={[0.739, 3.481, 1.012]} rotation={[0, 0, -Math.PI]} scale={[-0.288, -0.081, -0.016]} />
      <mesh geometry={nodes.Cube014.geometry} material={materials.Structure} position={[-0.155, 3.642, 1.392]} scale={0.03} />
      <mesh geometry={nodes.Cube015.geometry} material={materials.Structure} position={[-0.599, 3.237, 0.977]} scale={0.334} />
      <group position={[-0.701, 3.251, 1.014]} rotation={[0, 0, -0.006]} scale={[0.094, 0.239, 0.022]}>
        <mesh geometry={nodes.Cube018_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube018_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.2, 3.251, 1.014]} rotation={[0, 0, -0.006]} scale={[0.094, 0.239, 0.022]}>
        <mesh geometry={nodes.Cube019_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube019_2.geometry} material={materials.Material} />
      </group>
      <group position={[0.506, 4.538, 1.416]} rotation={[0, 0, 0.055]} scale={[0.112, 0.285, 0.026]}>
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube014_2.geometry} material={materials.Material} />
      </group>
      <group position={[-0.046, 3.251, 1.008]} rotation={[0, 0, -0.006]} scale={[0.094, 0.239, 0.022]}>
        <mesh geometry={nodes.Cube023_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube023_2.geometry} material={materials.Material} />
      </group>
      <group position={[1.222, 3.251, 1.014]} rotation={[0, 0, -0.006]} scale={[0.094, 0.239, 0.022]}>
        <mesh geometry={nodes.Cube024_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube024_2.geometry} material={materials.Material} />
      </group>
      <group position={[1.477, 3.234, 1.014]} rotation={[0, 0, -0.006]} scale={[0.084, 0.212, 0.019]}>
        <mesh geometry={nodes.Cube026_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube026_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cube026.geometry} material={materials['Post Officec']} position={[0.675, 3.839, 1.41]} rotation={[0, 0, -Math.PI]} scale={[-0.313, -0.142, -0.012]} />
      <mesh geometry={nodes.Cube002.geometry} material={materials['Brushed Copper']} position={[0.698, 7.562, 1.614]} scale={0.069} />
      <group position={[-1.223, 3.205, 0.738]} rotation={[1.571, -1.467, 1.564]} scale={[0.094, 0.239, 0.022]}>
        <mesh geometry={nodes.Cube029_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube029_2.geometry} material={materials.Material} />
      </group>
      <group position={[-1.223, 3.205, 0.285]} rotation={[1.571, -1.467, 1.564]} scale={[0.101, 0.257, 0.023]}>
        <mesh geometry={nodes.Cube030_1.geometry} material={materials.Windows} />
        <mesh geometry={nodes.Cube030_2.geometry} material={materials.Material} />
      </group>
      <mesh geometry={nodes.Cube030.geometry} material={materials.Structure} position={[-0.666, 2.448, 0.968]} rotation={[0, 0, 0.236]} />
      <mesh geometry={nodes.Cube020.geometry} material={materials.Wood} position={[-1.197, 2.7, 0.755]} rotation={[0.005, -0.001, -1.48]} scale={[2.454, 0.882, 1.954]} />
      <mesh geometry={nodes.Cylinder001.geometry} material={materials['Post Officec']} position={[0.429, 3.84, 1.434]} rotation={[Math.PI / 2, 0, 0]} scale={[0.016, 0.004, 0.016]} />
      <mesh geometry={nodes.Cube021.geometry} material={materials['Material.002']} position={[0.584, 3.069, 1.065]} scale={[0.023, 0.043, 0.015]} />
      <mesh geometry={nodes.Cube025.geometry} material={materials.Wood} position={[0.994, 2.368, 1.61]} scale={[0.044, 0.083, 0.044]} />
      <mesh geometry={nodes.Cube027.geometry} material={materials.Wood} position={[0.745, 3.034, 0.997]} scale={[0.232, 0.439, 0.018]} />
      <mesh geometry={nodes.Text.geometry} material={materials['Post Officec']} position={[0.677, 3.866, 1.435]} rotation={[Math.PI / 2, 0, 0]} scale={0.111} />
      <mesh geometry={nodes.Cube031.geometry} material={materials.Structure} position={[0.483, 2.448, 0.968]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube032.geometry} material={materials.Structure} position={[1.009, 2.448, 0.968]} scale={[0.03, 0.166, 0.03]} />
      <mesh geometry={nodes.Cube033.geometry} material={materials.Structure} position={[1.622, 2.448, 0.968]} scale={[0.03, 0.166, 0.03]} />
    </group>
  )
}

useGLTF.preload('/KlausHouse.glb')
