/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 Thebearcarmy.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/BibiModels/Thebearcarmy.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Quad_Sphere.geometry} material={materials.Skin} position={[0, 4.526, 0]} />
      <mesh geometry={nodes.Sphere.geometry} material={materials['Eyes (drawn)']} position={[0.336, 4.465, 0.985]} rotation={[1.638, 0, 0.001]} scale={0.239} />
      <mesh geometry={nodes.Circle.geometry} material={materials.Tshirt} position={[-0.014, 2.031, -0.245]} />
      <mesh geometry={nodes.Plane001.geometry} material={materials.Apron} position={[0.896, 2.219, -0.102]} rotation={[1.041, 0, 0]} scale={0.164} />
      <mesh geometry={nodes.Cube.geometry} material={materials.Apron} position={[-0.018, 1.012, 0.789]} rotation={[-0.259, 0, 0]} scale={[1.216, 0.473, 0.066]} />
      <mesh geometry={nodes.Sphere001.geometry} material={materials.Hair} position={[0, 5.008, -0.04]} scale={1.006} />
      <mesh geometry={nodes.Sphere002.geometry} material={materials.Hair} position={[0.192, 4.753, 1.381]} rotation={[0, 0, -0.084]} scale={0.073} />
      <group position={[0.334, 4.465, 1.018]} rotation={[-1.509, 0, 0.091]} scale={0.216}>
        <mesh geometry={nodes.Sphere003_1.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.Sphere003_2.geometry} material={materials.Material} />
        <mesh geometry={nodes.Sphere003_3.geometry} material={materials['Material.001']} />
      </group>
    </group>
  )
}

useGLTF.preload('/BibiModels/Thebearcarmy.glb')
